_target_: zse.models.adain_module.AdaINLitModule3D

net:
  _target_: zse.models.components.adain_unet.AdaINUNet
  vgg:
    _target_: torchvision.models.vgg19
    pretrained: True
  normalization:
    _target_: torchvision.transforms.Normalize
    mean: [0.485, 0.456, 0.406]
    std:  [0.229, 0.224, 0.225]
  unet_layers:  ['relu1_2', 'relu2_2', 'relu3_4', 'relu4_1']
  style_layers: ['relu1_2', 'relu2_2', 'relu3_4', 'relu4_1']
  out_channels: 1
  style_loss_fn: 'stats'
lr: 1e-4
weight_decay: 0
lr_decay: 1
style_weight: 1e1
small_style: True
