# https://www.tensorflow.org/tensorboard/

tensorboard:
  _target_: pytorch_lightning.loggers.tensorboard.TensorBoardLogger
  save_dir: "${original_work_dir}/logs/tensorboard"
  name: ${name}
  version: null
  log_graph: False
  default_hp_metric: False
  prefix: ""
